---
  - name: save show configuration output
    hosts: all
    vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
      - ../../inventory/group_vars/extream.yml
    gather_facts: no
    vars:
      folder: show_config
      file_name: "{{ lookup('pipe', 'date +%Y%m%d') }}_{{ inventory_hostname }}"

    tasks:
      - name: run show configuration on remote devices
        ios_command:
          commands: show configuration
        register: show_config_output

      - name: create directory for show configuration output
        file:
          path: "{{path}}/{{folder}}"
          state: directory

      - name: save show configuration output to file
        copy:
          content: "{{ show_config_output.stdout[0] }}"
          dest: "{{path}}/{{folder}}/{{ file_name }}.txt"

# ansible-playbook ./playbook/extream/show_config.yml -i ./inventory/extream_hosts