---
  - name: save show version output
    hosts: all
    vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
      - ../../inventory/group_vars/extream.yml
    gather_facts: no
    vars:
      folder: show_port
      file_name: "{{ lookup('pipe', 'date +%Y%m%d') }}_{{ inventory_hostname }}"


    tasks:
      - name: run show port on remote devices
        ios_command:
          commands: show port no-refresh
        register: show_port_output

      - name: create directory for show port output
        file:
          path: "{{path}}/{{folder}}"
          state: directory

      - name: save show port output to file
        copy:
          content: "[{{ inventory_hostname }}]\n{{ show_port_output.stdout[0] }}"
          dest: "{{path}}/{{folder}}/{{ file_name }}.txt"

# ansible-playbook ./playbook/extream/show_port.yml -i ./inventory/extream_hosts