---
- name: Fortigate Static Rouing 생성
  hosts: all
  vars_files:
    - ../../inventory/group_vars/fortigate.yml
    - ../../vars/forti_vars.yml
  connection: httpapi
  gather_facts: false
  collections:
      - fortinet.fortios

  tasks:
    - name: Configure Static Route
      fortinet.fortios.fortios_router_static:
        vdom: "root"
        access_token: "{{ fortios_access_token }}"
        state: "present"                  # present: 생성/갱신, absent: 제거
        router_static:
          seq_num: "{{ item.seq_num }}"
          dst: "{{ item.dst }}"
          gateway: "{{ item.gateway }}"
          device: "{{ item.device }}"
          distance: "{{ item.distance }}"
          priority: "{{ item.priority }}"
          comment: "{{ item.comment }}"
      loop: "{{ xxx }}"                 # 사용 시 맞는 변수명을 넣어 사용할 것 - static_routes_branch 등


# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook ./playbook/fortigate/create_routing_static.yml -i ./inventory/forti_hosts
# https://docs.ansible.com/ansible/latest/collections/fortinet/fortios/fortios_router_static_module.html