---
- name: Fortigate IPsecVPN 목록 확인
  hosts: all
  vars_files:
    - ../../inventory/group_vars/fortigate.yml
  connection: httpapi
  gather_facts: false
  vars:
    folder: routing_table

  tasks:
    - name: Query FortiGate routing table
      ansible.builtin.uri:
        url: "https://{{ ansible_host }}/api/v2/cmdb/router/static?vdom=root"
        method: GET
        headers:
          Authorization: "Bearer {{ fortios_access_token }}"
        validate_certs: false
        return_content: true
      register: static_routes_result

    # command line으로 확인 시
    # - name: Routing Table result
    #   debug:
    #     var: static_routes_result.json

    # txt 파일로 저장 시
    - name: Format routing table as text
      ansible.builtin.set_fact:
        routing_table: |
          Routing Table for {{ inventory_hostname }}
          ---------------------------------------------------------------
          {{ "%-9s %-18s %-18s %-18s %-18s %-10s %-10s" | format("SEQ-NUM", "ADDRESS", "SUBNET", "GATEWAY", "INTERFACE", "DISTANCE", "PRIORITY") }}
          {% for route in static_routes_result.json.results %}
          {% set dst_parts = route.dst.split(' ') %}
          {% set address = dst_parts[0] %}
          {% set subnet = dst_parts[1] %}
          {% set priority = route['priority'] if 'priority' in route else '-' %}
          {{ "%-9s %-18s %-18s %-18s %-18s %-10s %-10s" | format(route['seq-num'], address, subnet, route.gateway, route.device, route.distance, priority) }}
          {% endfor %}

    # csv 파일로 저장 시
    # - name: Format routing table as csv
    #   ansible.builtin.set_fact:
    #     routing_table: |
    #       SEQ-NUM,ADDRESS,SUBNET,GATEWAY,INTERFACE,DISTANCE,PRIORITY,COMMENT
    #       {% for route in static_routes_result.json.results %}
    #       {% set dst_parts = route.dst.split(' ') %}
    #       {% set address = dst_parts[0] %}
    #       {% set subnet = dst_parts[1] %}
    #       {% set priority = route['priority'] if 'priority' in route else '-' %}
    #       {{route['seq-num']}},{{address}}, {{subnet}}, {{route.gateway}}, {{route.device}}, {{route.distance}}, {{priority}},{{route.comment}}
    #       {% endfor %}

    - name: Create directory for show route output
      ansible.builtin.file:
        path: "{{path}}/{{folder}}"
        mode: "0755"
        state: directory

    - name: Save route list
      ansible.builtin.copy:
        content: "{{ routing_table | trim }}"
        mode: "0644"
        dest: "{{ path }}/{{ folder }}/{{ file_name }}.txt"
        # dest: "{{ path }}/{{ folder }}/{{ file_name }}.csv"


# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook ./playbook/fortigate/show_routing-static.yml -i ./inventory/forti_hosts