---
  - name: Fortigate IPsecVPN 목록 확인
    hosts: all
    vars_files:
      - ../../inventory/group_vars/fortigate.yml
    connection: httpapi
    gather_facts: no
    vars:
      folder: routing_table
      file_name: "{{ lookup('pipe', 'date +%Y%m%d') }}_{{ inventory_hostname }}"

    collections:
      - fortinet.fortios

    tasks:
      - name: Query FortiGate routing table
        uri:
          url: "https://{{ ansible_host }}/api/v2/monitor/router/ipv4?vdom=root"
          method: GET
          headers:
            Authorization: "Bearer {{ fortios_access_token }}"
          validate_certs: no
          return_content: yes
        register: routing_result
      
      # command line으로 확인 시
      # - name: Routing Table result
      #   debug:
      #     var: routing_result.json
      
      - name: Format routing table as text
        set_fact:
          routing_text: |
            Routing Table for {{ inventory_hostname }}
            ---------------------------------------------------------------
            {{ "%-20s %-18s %-18s %-10s %-10s %-10s" | format("DESTINATION", "GATEWAY", "INTERFACE", "DISTANCE", "PRIORITY","TYPE") }}
            {% for route in routing_result.json.results %}
            {% set priority = route['priority'] if 'priority' in route else '-' %}
            {{ "%-20s %-18s %-18s %-10s %-10s %-10s" | format(route.ip_mask, route.gateway, route.interface, route.distance, priority,route.type) }}
            {% endfor %}

      - name: create directory for show route output
        file:
          path: "{{path}}/{{folder}}"
          state: directory

      - name: Save route list as TXT (table)
        copy:
          content: "{{ routing_text | trim }}"
          dest: "{{ path }}/{{ folder }}/{{ file_name }}.txt"

# OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES ansible-playbook ./playbook/fortigate/show_routing_all.yml -i ./inventory/forti_hosts