---
- name: user_add
  hosts: all
  vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
    - ../../inventory/group_vars/f5.yml
  connection: local
  gather_facts: no

  collections:
   - f5networks.f5_modules
  
  tasks:
    - name: add user
      bigip_user:
        provider: '{{ f5_provider }}'
        username_credential: '{{ id_username }}'
        password_credential: '{{ id_password }}'
        # full_name: '{{ description }}'
        partition_access: '{{ role }}'
        shell: '{{ terminal_access }}'
        update_password: on_create
        state: absent  #delete->absent
      delegate_to: localhost

    # - name: Sync configuration from device to group
    #   bigip_configsync_action:
    #     provider: '{{ f5_provider }}'
    #     device_group: DG
    #     sync_device_to_group: yes
    #   delegate_to: localhost