---
- name: create service
  hosts: all
  vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
    - ../../inventory/group_vars/f5.yml
  connection: local
  gather_facts: no

  collections:
   - f5networks.f5_modules
  
  tasks:
      - name: add node                    # node만 생성 시, 기존 등록된 node가 없을 경우 pool member 생성 시 자동 생성 
        bigip_node:
          host: "{{ item.host }}"
          name: "{{ item.host }}"
          provider: '{{ f5_provider }}'
        delegate_to: localhost
        loop:
          - { host: 10.225.29.41}
          - { host: 10.225.29.41}