---
- name: user_add
  hosts: all
  vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
    - ../../inventory/group_vars/dell.yml
  gather_facts: no

  collections:
   - dellemc.os9
  
  tasks:
    - name: configuration user add
      dellos9_config:
        lines:
          - username {{ add_username }} privilege 15 secret {{ add_password }}
          # - no username {{ del_username }}
        save: yes