---
  - name: save show run acl output
    hosts: all
    vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
      - ../../inventory/group_vars/dell.yml
    gather_facts: no
    collections:
      - dellemc.os9

    tasks:
      - name: show mac address on remote devices
        dellos9_command:
          commands: show mac-address-table | grep d1:ba
        register: show_mac

      - debug: var=show_mac.stdout_lines

      # - name: create directory for show run acl output
      #   file:
      #     path: "{{path}}/show_run_acl"
      #     state: directory

      # - name: save show run acl output to file
      #   copy:
      #     content: "{{ show_run_acl_output.stdout[0] }}"
      #     dest: "{{path}}/show_run_acl/{{ inventory_hostname }}_show_run_acl.txt"