---
  - name: save show run acl output
    hosts: all
    vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
      - ../../inventory/group_vars/dell.yml
    gather_facts: no
    vars:
      folder: show_multi_command
      file_name: "{{ lookup('pipe', 'date +%Y%m%d') }}_{{ inventory_hostname }}"
    collections:
      - dellemc.os9

    tasks:
      - name: show vrrp brief on remote devices
        dellos9_command:
          commands: show vrrp brief
        register: show_vrrp_brief_output
        ignore_errors: yes # 명령어 출력 결과가 없을 때 에러가 발생해도 다음 작업으로 넘어가는 명령어

      # - debug: 
      #     var: show_vrrp_brief_output.stdout

      - name: show run spanning-tree pvst on remote devices
        dellos9_command:
          commands: show spanning-tree rstp brief
        register: show_spanning_tree_pvst_output
        ignore_errors: yes

      - name: show run on remote devices
        dellos9_command:
          commands: show run
        register: show_run_output

      - name: create directory for show run acl output
        file:
          path: "{{path}}/{{folder}}"
          state: directory

      - name: save show run multi command output to file
        copy:
          content: "
          {% if show_vrrp_brief_output.stdout[0] is defined %}
          
          * show_vrrp_brief *\n
          {{ show_vrrp_brief_output.stdout[0] }}\n\n
          ==================================

          {% endif %}
          * show_spanning_tree_pvst *\n
          {{ show_spanning_tree_pvst_output.stdout[0] }}\n\n
          ==================================
          
          * show_run * \n\n
          {{ show_run_output.stdout[0] }}"
          dest: "{{path}}/{{folder}}/{{ file_name }}.txt"