---
- name: create_address_object
  hosts: all
  vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
    - ../../inventory/group_vars/paloalto.yml
    - ../../vars/pafw_vars.yml
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos
  
  tasks:
    # address object 생성
    - name: Create service object
      panos_service_object:
        provider: '{{ palo_provider }}'
        name: '{{ item.name }}'
        destination_port: '{{ item.port }}'
        protocol: udp
        # description: '{{ item.description }}'
        # tag: ['panos']
        # state: 'absent'                         # absent : Delete
      loop: "{{ service_object }}"

    # - name: commit config on firewall
    #   panos_commit_firewall:
    #     provider: '{{ palo_provider }}'
    # - debug: msg='{{ result.rule }}'

# https://ansible-pan.readthedocs.io/en/latest/modules/panos_service_object_module.html