---
- name: change management
  hosts: all
  vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
    - ../../inventory/group_vars/paloalto.yml
  vars:
    - address : 1.1.1.1/32
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos
  
  tasks:

  # user 추가
    - name: Remove an address object using delete
      panos_type_cmd:
        provider: '{{ palo_provider }}'
        xpath: |
          /config/devices/entry[@name='localhost.localdomain']
          /deviceconfig/system/permitted-ip/entry[@name='{{address}}']
        cmd: delete

    #작업 상태 확인
    - name: check if ready
      panos_check:
        provider: '{{ palo_provider }}'
        timeout: 0

    # commit 진행
    - name: commit config on firewall
      panos_commit_firewall:
        provider: '{{ palo_provider }}'
      