---
- name: create_address_object
  hosts: all
  vars_files: # 변수 파일 지정, 미 사용시 인벤토리 호스트 그룹명과 group_vars 파일명이 일치하는 파일 자동매칭 사용
    - ../../inventory/group_vars/paloalto.yml
    - ../../vars/pafw_vars.yml
  connection: local
  gather_facts: no

  collections:
    - paloaltonetworks.panos
  
  tasks:
  # address object 생성
  - name: Create address object
    panos_address_object:
      provider: '{{ palo_provider }}'
      name: '{{ item.name }}'
      value: '{{ item.value }}'
      description: '{{ item.description }}'
      # IP Range 등록 시
      # address_type: 'ip-range'
      # value: '1.1.1.1-2.2.2.2'
      # tag: ['panos']
      # state: 'absent' # absent : Delete
    loop: "{{ address_object }}"

  # address group object 생성
  - name: Create object group
    panos_address_group:
      provider: '{{ palo_provider }}'
      name: 'hotel'
      static_value: ['10.100.1.1','10.100.1.2']
      # state: 'absent' # absent -> Delete

  - name: commit config on firewall
    panos_commit_firewall:
      provider: '{{ palo_provider }}'
  - debug: msg='{{ result.rule }}'

# https://ansible-pan.readthedocs.io/en/latest/modules/panos_address_object_module.html